on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

name: Conformance
jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout conformance client
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run test suite
        uses: theupdateframework/tuf-conformance@f4acd16d0ea49a6fd5cc4558084b578c6fc7d6cd # v2.0.0
        with:
          entrypoint: ".github/scripts/conformance-client.py"
